### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by abstractwilly** [seenickcode/fluttercrashcourse-lessons#1]
using your same code,i tried but it shows   'undefined MyApp' and 'unused import file'.
how to fix this error?

**Comment by idkjs** [comment]
@abstractwilly hard to tell what you are talking about here. Any additional details you can provide?

**Comment by djdeo** [comment]
I got the issue here, when we edit in `main.dart` file with the same code, we get error @abstractwilly  listed in `widget_test.dart` file;

If we edit change **MyApp()** to **LocationDetail()**,  and import it, the error disappear, but the `body` of **Scaffold** is not rendered in the emulators

**Comment by AdamDKing** [comment]
For posterity:

I think willy's problem is that he started a new dart project, which created a bunch of sample files, and then he only overwrote some of those files.  The sample 'widget_test.dart' makes reference to a 'MyApp' found in the sample 'main.dart'.  After replacing the sample contents of 'main.dart' with the code for fluttercrashcourse, 'MyApp' is no longer defined.  This shouldn't interfere with the functioning of your app, but if it does, you can safely delete the offending 'widget_test.dart' sample file.

Willy's problem doesn't seem related to djdeo's problem, which I'm not sure how to solve.

**Comment by rustkas** [comment]
One of the ways to escape such problems: 
1. Download the source code.
2. Create new new project and carefully paste the texts of source code to new one.

Opening old projects by evergreen IDE is not recommended.
