### ISSUE TITLE
dotNet with Flutter

### ISSUE THREAD

**Issue by KaloyanBouresh** [seenickcode/fluttercrashcourse-lessons#10]
**Describe the bug**
Practically my issue is not a bug. I have a question how to implement parent - child classes in Flutter with C#/.Net backend.
I have made a simple backend Rest Api with .NET 5. The program is: A parent class House with id, number of floors, adress and list of child class objects - devices. The child class Device has it's own id, floor(the floor, which this device is), place(Bedroom, Bathroom an so on) and Device type. DeviceType is a class, that contains a name(ex. Air conditioner) and powerW(ex. 1700 W).
Made the CRUD, everything is working perfectly. When I want to get a house there is a json file with the data of the house, a nested list of devices, and for every device another nested object of device type.
So far so good. But I wanted to make a fronted with Flutter. The idea is as follows:
Home screen is a list of houses, named by their id. When a given house is clicked it goes to second screen where there is a data for the house- text editing fields with adress and number of floors. I want to make another field with a dropdown menu of devices, but there is the problem- I don't know how...

Here are my classes in dart:

//import 'device.dart';

class House {
  int _id;
  String _adress;
  int _floorsCnt;
  //List<Device> _devices;

  House(this._adress, this._floorsCnt);
  House.WithId(
    this._id,
    this._floorsCnt,
    this._adress,
    
  );

  int get id => _id;
  String get adress => _adress;
  int get floorsCnt => _floorsCnt;
  //List<Device> get devices => _devices;

  set adress(String newAdress) {
    _adress = newAdress;
  }

  set floorsCnt(int newfloorsCnt) {
    _floorsCnt = newfloorsCnt;
  }

  // set devices(List<Device> newDevices) {
  //   _devices = newDevices;
  // }

  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{};
    map["floorsCnt"] = _floorsCnt;

    map["adress"] = _adress;

   // map["devices"] = _devices;

    if (_id != null) {
      map["id"] = _id;
    }
    return map;
  }

  House.fromObject(dynamic o) {
    _id = o["id"];
    _floorsCnt = o["floorsCnt"];
    _adress = o["adress"];
   // _devices = o["devices"];
  }
}

------------------------------------

// ignore_for_file: non_constant_identifier_names

import 'package:house_ui/models/house.dart';

import 'device_type.dart';

class Device {
  int _id;
  int _floor;
  //DeviceType _deviceType;
  int _house_id;
  House _house;

  Device(this._floor, this._house_id,this._house);
  Device.WithId(this._id, this._floor, this._house_id, this._house);

  int get id => _id;
  int get floor => _floor;
  // DeviceType get deviceType =>_deviceType;
  int get houseId => _house_id;
  House get house => _house;

  set floor(int newFloor) {
    _floor = newFloor;
  }

  set houseId(int newHouseId) {
    _house_id = newHouseId;
  }

  set house(House newHouse) {
    _house = newHouse;
  }

  //to set deviceType

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map["floor"] = _floor;

    map['houseId'] = _house_id;

    map['house'] = house;

    if (_id != null) {
      map["id"] = _id;
    }
    return map;
  }

  Device.fromObject(dynamic o) {
    _id = o["id"];
    _floor = o["floor"];
    _house_id = o['houseId'];
    _house = o['house'];
  }
}
-------------------------------------------

import 'device.dart';

class DeviceType {
  int _id;
  String _name;
  int _power_w;
  //int _device_id;
  // Device _device;

  //DeviceType( this._id, this._name, this._power_w, this._device_id, this._device);
  DeviceType(this._name, this._power_w);
  DeviceType.WithId(this._id, this._name, this._power_w);

  int get id => _id;
  String get name => _name;
  int get power_w => _power_w;

  set name(String newName) {
    _name = newName;
  }

  set power_w(int newPowerW) {
    _power_w = newPowerW;
  }

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map["name"] = _name;
    map["powerW"] = _power_w;
    if (_id != null) {
      map["id"] = _id;
    }
    return map;
  }

  DeviceType.fromObject(dynamic o) {
    this._id = o["id"];
    this._name = o["name"];
    this._power_w = o["powerW"];
  }
}

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by seenickcode** [comment]
Hi there could you please post the code on a repository so I can look at it
it’s very difficult of you but I just pasting it in here thank you so much

**Comment by seenickcode** [comment]
… sorry, I meant to say it’s extremely difficult to read through the code
when it’s pasted in. Could you please post it on a repository somewhere?
thank you!

**Comment by KaloyanBouresh** [comment]
Yeah, sure! I'll post it today and share it with you.

**Comment by KaloyanBouresh** [comment]
Hello, may I sent you link as this:

https://github.com/KaloyanBouresh/HouseAPi.git
Thanks.
If there' s any issue, text me!

На нд, 9.01.2022 г. в 12:24 ч. kaloyan bouresh ***@***.***>
написа:

> Yeah, sure! I'll post it today and share it with you.
>
>

**Comment by seenickcode** [comment]
The link is broken. Closing for now. Lmk!
