### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by svoboda01** [seenickcode/fluttercrashcourse-lessons#12]
**Describe the bug**
In the Tourism & Co. code from the Github repository starting with Lesson 12, the app fails to build due to version solving issues.

**To Reproduce**
1. Download the latest code from https://github.com/seenickcode/fluttercrashcourse-lessons
2. In a terminal window, navigate to /module02-tourismandco/lesson12
3. Type 'flutter run'
4. Choose a device on which to launch the application (i.e. iPhone simulator)
5. See error in the screenshot below ```pub get failed (1; So, because lesson12 depends on both test any and
build_runner ^2.0.0, version solving failed.)```

**Expected behavior**
The app will launch without error.

**Screenshots**
<img width="891" alt="Screen Shot 2022-08-02 at 7 06 47 AM" src="https://user-images.githubusercontent.com/18353721/182361919-39afb3ed-3fff-4c77-b466-7a20dec57322.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.5 Monterey

**Comment by seenickcode** [comment]
Fixed with latest MR merged. Thanks for reporting.
