### ISSUE TITLE
Compiler failed

### ISSUE THREAD

**Issue by ghost** [seenickcode/fluttercrashcourse-lessons#2]
I am getting this error:

Compiler message:
lib/main.dart:7:7: Error: No named parameter with the name 'appbar'.
      appbar: AppBar(
      ^^^^^^
file:///home/nikhil/development/flutter/packages/flutter/lib/src/material/scaffold.dart:889:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({

**Comment by ins4w** [comment]
A little bit late but just in case, it's supposed to be appBar, no appbar.

**Comment by seenickcode** [comment]
Ok thanks!
