### ISSUE TITLE
In Advanced Flutter section, video# 27 - #49 are not playing

### ISSUE THREAD

**Issue by echo-harshal** [seenickcode/fluttercrashcourse-lessons#21]
**Describe the bug**
A clear and concise description of what the bug is. [This article](https://stackoverflow.com/help/minimal-reproducible-example) provides a great overview on how best to describe the problem and provide a reproducible example.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by echo-harshal** [comment]
@seenickcode

**Comment by seenickcode** [comment]
Please try again, it should be fixed now.
