### ISSUE TITLE
mock_location.dart ERROR because constructor is missing. 

### ISSUE THREAD

**Issue by YToprak** [seenickcode/fluttercrashcourse-lessons#7]
![Bildschirmfoto 2022-01-06 um 15 20 32](https://user-images.githubusercontent.com/31251593/148397321-88017af5-8ba9-49eb-a72a-da129adde2b0.png)

You rewritten Code in Video is not describing this failure. I can't not compile my Code at runtime.
I have problem with the Mockdata as you can see. 
I have to identify a Constructor but you Video is not showing any Constructor on the Mockdata.

**Comment by seenickcode** [comment]
Hello @YToprak, thank you for reporting. Please follow the issue template cited here https://github.com/seenickcode/fluttercrashcourse-lessons/issues/new?assignees=&labels=&template=bug_report.md&title= and ensure you are providing enough details. Especially a link to the codebase so I can reproduce. 

Take a look at this later lesson for example for a more built out version of `MockLocation`.

https://github.com/seenickcode/fluttercrashcourse-lessons/tree/master/module02-tourismandco/lesson18

**Comment by seenickcode** [comment]
Feel free to re-open when you have sufficient details, thank you.
