### ISSUE TITLE
Issue with empty List List<Widget> is deprecated

### ISSUE THREAD

**Issue by YToprak** [seenickcode/fluttercrashcourse-lessons#8]
**Describe the bug**
A clear and concise description of what the bug is. [This article](https://stackoverflow.com/help/minimal-reproducible-example) provides a great overview on how best to describe the problem and provide a reproducible example.

**To Reproduce**
Steps to reproduce the behavior
1. Go to 'location_detail.dart'
2. Click on List Widget _renderFacts
3. See ![Bildschirmfoto 2022-01-06 um 15 39 37](https://user-images.githubusercontent.com/31251593/148399771-f13bde86-20f2-4667-b932-afc1c2f298df.png)

**Comment by seenickcode** [comment]
Hello, there a many versions of location_detail.dart in this repo so I have no way of seeing what file you are referring to.

Please follow the issue template cited here https://github.com/seenickcode/fluttercrashcourse-lessons/issues/new?assignees=&labels=&template=bug_report.md&title= 

Thank you

**Comment by seenickcode** [comment]
Closing for now until more information is provided.
