### ISSUE TITLE
dead Image Link: master/module01-thebasics/lesson04/lib/mocks/mock_location.dart

### ISSUE THREAD

**Issue by YToprak** [seenickcode/fluttercrashcourse-lessons#9]
**Describe the bug**
A clear and concise description of what the bug is. [This article](https://stackoverflow.com/help/minimal-reproducible-example) provides a great overview on how best to describe the problem and provide a reproducible example.

**To Reproduce**
1. Go to '.mock_location.dart'
2. Click on 'Image which provided.'
4. See error dead link from Image to your site, please update repo.

**Comment by seenickcode** [comment]
Hello, thanks for reporting. I've just updated 'master' with the fix. https://github.com/seenickcode/fluttercrashcourse-lessons/blob/master/module01-thebasics/lesson04/lib/mocks/mock_location.dart#L8
